### ISSUE TITLE
Promote AdoptOpenJDK Version 11.0.5+10 (GA) and 8u232-b09 (GA)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#119]
# Release Order

We will release the following versions/platforms in the order listed below although this may be subject to change on the day of the release.

Please see the #release channel in the adoptopenjdk.net/slack for coordination efforts.

## jdk8u232-b09 - Phase 1

**Hotspot JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

**OpenJ9 JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

----

## 11.0.5+10 - Phase 1

**Hotspot JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

**OpenJ9 JVM**
- [x] x64Linux
- [x] x64Mac
- [x] x64Windows

----

##  jdk8u232-b09 - Phase 2

**Hotspot JVM**
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [x] sparcv9Solaris
- [x] x64Solaris
- [x] arm32Linux

**Hotspot JVM**
- [x] aarch64Linux

**OpenJ9 JVM:**
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL
- [x] x64WindowsXL

----

##  11.0.5+10 - Phase 2

**Hotspot JVM**
- [x] x32Windows
- [ ] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [ ] aarch64Linux
- [x] arm32Linux

**OpenJ9 JVM:**
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL
- [x] x64WindowsXL

**Comment by lumpfish** [comment]
Openj9 status on jdk8u and jdk11u so far:


jdk11u:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/613/console


linux_xl - all triaged
Failures:
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)


linux_x64 - all triaged
Failures:
special.functional: AdoptOpenJDK/openjdk-tests#1394 (new)
sanity.openjdk
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)
sun/util/calendar/Bug6653944.java  failed - passed on rerun: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/815/console


winxl - all triaged
sanity.openjdk failed due to infrastructure issue: AdoptOpenJDK/openjdk-infrastructure#962
Resubmitted : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/824/
Failures:
sanity.openjdk
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1396 (new) - test setup issue?


linux_s390x - all triaged
Failures:
sanity.openjdk
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)


aix
build failed due to Resources temporarily unavailable
Resubmitted: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/614/
Resubmitted build failed: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/381/
Raised https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/965
Resubmitted again: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/618/. Buillt OK


openliberty-mp-tck_x86-64_linux: - all triaged
all OK


windows_64 - all triaged
Failures:
sanity.openjdk:
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)
extended.system: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_windows/50/
Test failed : SharedClasses.SCM23.MultiThread_0:**FAILED** Process MT4 has timed out.
See comments above
Passed on rerun: https://ci.adoptopenjdk.net/job/Grinder/816/


linux_ppc64le - all triaged
Failures:
sanity.openjdk:
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)


mac_x86-64 - all triaged
Failures:
sanity.openjdk :
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)
extended.system:
Test failed : SharedClasses.SCM23.MultiThread_0:**FAILED** Process MT4 has timed out.
See comments above
Passed on rerun: https://ci.adoptopenjdk.net/job/Grinder/817/


mac_xl_x86-64- all triaged
Failures:
sanity.openjdk:
eclipse/openj9#6802 (old)
eclipse/openj9#7167 (old)


jdk8u:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/728/console


aix-ppc64:
extended.system and sanity.openjdk
 failed to run: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_ppc64_aix/2/console
 Raised AdoptOpenJDK/openjdk-infrastructure#963
sanity.system
extended.system rerun: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/818/
sanity.openjdk rerun: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/823/
Failures:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1011 (old)


linux-x64: all triaged
Build failed due to generated_configure.sh failure: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/435/console
Raised AdoptOpenJDK/openjdk-infrastructure#961
AdoptOpenJDK/openjdk-infrastructure#961 fixed (pipeline change)
Build resubmitted: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/442
Failures:
sanity.perf: https://github.com/eclipse/openj9/issues/7452 (old but recent)
sanity.external: https://github.com/eclipse/openj9/issues/6435 (old)


linuxXL - all triaged
 all OK


linux-ppc64le
 - all triaged
 all OK


linux_s390x - all triaged
 all OK


mac-x64 - all triaged
 all OK


macosXL - all triaged
 all OK


windows-x86-32 - all triaged
 all OK


windows-x64 - all triaged
 all OK


windowsXL - all triaged
 all OK

**Comment by andrew-m-leonard** [comment]
jdk8u232-b09_openj9-0.17.0 published all platforms
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u232-b09_openj9-0.17.0

**Comment by karianna** [comment]
I’m happy with 11.0.5 Hotspot for:

• mac x64
• windows x64
• linuxx64

Only test failures are environmental or P3's (some minor TZ data failures for JP and KR) (edited)

 I’m happy with jdk8  builds for:

• ppc64le_linux
• s390x_linux (one test should be looked at in more depth but it’s not a P1)
• x86-32_windows
• mac x64
• windows x64
• linuxx64
• solarisx64
• solarisSparc (edited) 

Only very minor environmental failures

**Comment by karianna** [comment]
11.0.5 secondary platforms for Hotspot are a bit of a disaster.

Win32 is through
s390 is through (although 48 failing tests due to environmental issues)

Re spinning everything else.

**Comment by karianna** [comment]
ppc64le and arm32 for 11.0.5+10 HS are released

**Comment by smlambert** [comment]
Looking for links to the pipelines for the hotspot AIX attempts...  slack conversations references but does not give link.
