### ISSUE TITLE
Ensure all of our repositories are documented

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/TSC#139]
(I thought I already had an issue for this but I can't find it...)

We have over 100 repositories now. We should ensure that all are needed. They come into three categories:

1. `binaries` releases where we store our artefacts
2. "Core" parts of the adoptopenjdk build/test infrastructure (Mostly the ones prefixed `openjdk-`)
3. Other stuff including IcedTea-WEB etc.

We should do a review of them and ensure that the ones in categories 2 and 3 are still required and appropriately documented. There is a list in the README.md in this repository but I suspect it's missing quite a few of the repositories which we have.

**Comment by smlambert** [comment]
I am going through the Top Priorities project to settle on no more than 3 issues per repo and to clear out issues that are not actually being addressed in a timely fashion (indicating we do not actually view them as top priority).  This issue has been around for a while, @karianna @sxa - I will move it out of the Top Priorities project, unless its active. 

I am looking at #104, #158 and #178 as top 3 for TSC repo, but can be convinced otherwise.

**Comment by sxa** [comment]
I bug @karianna periodically to review the details I sent to him. I consider this a top priority for the project to understand what we've got prior to moving to eclipse if nothing else.

**Comment by smlambert** [comment]
Ok, so what action has to happen here, reviewing of documentation details?  Can others on TSC help (where are the details)?

**Comment by karianna** [comment]
I'm going to look at the finances today and hopefully this as well (if not its tomorrow mornings work)

**Comment by karianna** [comment]
Done at Adoptium
