### ISSUE TITLE
Inital TSC Board

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#2]
We are looking for 9 initial members of the AdoptOpenJDK TSC.

Please consider the rules/guidelines in https://github.com/AdoptOpenJDK/TSC/pull/1

I will set the initial deadline for nominations to be 12:00 GMT 23/06/2017. Feel free to nominate yourself or other people. You can nominate as many people as you like. Once the deadline has been reached an online election tool will be configured and a link shared for all members to vote.

If you nominate yourself or have been nominated then please try to add a brief manifesto explaining where you would like the project to go in the future

**Comment by gdams** [comment]
I am going to go ahead and nominate @tellison and @karianna as TSC members

**Comment by bblondin** [comment]
I will second that. Nominating @tellison and @karianna

**Comment by karianna** [comment]
I'm going to go ahead and nominate @smlambert

**Comment by tellison** [comment]
Curious about how the number nine was chosen for size of a TSC?

We can easily name the folks who have been solid contributors over the last few months.  I guess not all may want to participate in discussing the project direction, rather than focused on getting stuff actually working!

Thanks for the nomination.  I'm happy to write a manifest - but beware it may turn into "war and peace" ;-)

We can't have a TSC without the folks that are already investing in the project direction, @gdams, @karianna, @neomatrix369, @Joe-Brady, @bblondin, @smlambert

**Comment by gdams** [comment]
Umm I initially drafted 9 because I felt that 9 was a great number, happy to change that though

**Comment by Joe-Brady** [comment]
@tellison 
Happy to be involved, and I would occasionally have opinions on project direction I'm sure, but at the same time I'm quite happy to just continue chipping away at the website and API - 'focused on getting stuff working' like you say 😄

**Comment by smlambert** [comment]
Also happy to be involved and have a great many thoughts/opinions on the topic of testing, and will try to keep a manifest to a slightly shorter Tolstoy/Ellison novel.  I will say that I have already summarized our goals and motivation at https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/README.md in the "What is our motivation?" section.

**Comment by gdams** [comment]
closing in favour of https://github.com/AdoptOpenJDK/TSC/issues/9
