### ISSUE TITLE
Adopt Community Call - 22nd of February 2021

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/TSC#202]
**Time**

4-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Meeting Agenda**

- Name of the Meeting
Opportunity for folks to propose new names if needed. 
- Time, date, and length of the meeting.
Opportunity for folks to propose new times and/or dates. 
- Location + Format of Agenda
Any debate over whether this is in the correct repo, and whether the format should be changed.
Template for future agenda issues to be created once repo + format has consensus.
- Meeting Invite
Could there be a meeting invite for this meeting? 
- Future topics
What do people want to hear about at the next meeting?
Who could be asked to provide a briefing on these topics?

Note: Further agenda items can be added via comments.

- AOB

**Comment by adamfarley** [comment]
Meeting Notes:
- Adam Brousseau reports difficulty using his own repos after the build repo split. Build runs keep fetching Adopt's repos.
Morgan noted to be working on a fix.
- Credential parameters for ssh git clones (git@etc.etc) aren't always used during builds
SSH agents aren't always used where they need to be used, so authenticated actions fail.
- Meeting name proposed to be the Adoptium Community Call.
- Formerly explicit XL (large heap vs not) and compressedrefs (compressed address references vs not) openj9 VMs are to be combined into a single VM capable of handling both. Nomenclature: "Mixed References".
- Meeting Time +date, frequency, agenda format, etc is fine.

Topics for the next session:
- A summary on the repo split is requested. How things are split now, plans for the future. 
Morgan and/or George to be asked to provide a briefing at the next community call.
- A summary on "mixed references" is requested.
Specialist to be identified.
- Shelley to update us on how Eclipse want meetings to be scheduled re: peoples' calendars.
- Shelley to continue to perform a running summary on the transition to Adoptium.
- The student group/UX team to provide a summary on their website improvement work when new info is to be had.

**Comment by smlambert** [comment]
Thanks for taking notes @adamfarley 

A few additional notes relating to the update on the transition to Eclipse Foundation:
- Adoptium Working Group and Eclipse Foundation are working through a transition document for next steps
- Adoptium (top-level project & WG) - repos like website and blog will go here (initial CQs to be created this week)
  - Temurin - repos related to building consumable artifacts go here (initial CQs to be created this week)
  - Temurin-compliance - private repos containing TCK material go here (no CQs for this material, not public)
  - AQAvit - test repos go here (Initial CQs created for all 7 test repos)

- In order to maintain continuity and to allow consumers time to acclimatize to our transition, the plan is to keep the ability to build and release out of both AdoptOpenJDK and Adoptium for at least 1 release period (this should protect us from any unforeseen issues or hiccups that may block us from releasing from new Jenkins server and lifted/renamed/moved repos at Eclipse foundation).  

Meeting [recording link](https://bluejeans.com/s/dEcTqlxDbQ5/)

Next call's issue and proposed agenda found in https://github.com/AdoptOpenJDK/TSC/issues/203
