### ISSUE TITLE
Bi-weekly Adoptium Community Call - March 22, 2021

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#207]
**Time**

4-5pm GMT (12pm-1pm EST/Ontario this week due to daylight savings happening sooner in Canada)

**Location**
https://bluejeans.com/956754991/2833?src=calendarLink

Add this [recurring bi-weekly Adoptium Community Call](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL) to your calendar, if you wish.

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community with emphasis on non-test efforts, as those are covered in the bi-weekly AQAvit meeting.  Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda**
- EF transition update
- website progress
- JDK16 release summary
- Review "[Top Priorities](https://github.com/orgs/AdoptOpenJDK/projects/1)" issues 
- ... add comments below to add items to the agenda

**Comment by aahlenst** [comment]
Go over the top priorities. We manage to skip that in every type of meeting we have 😁

**Comment by smlambert** [comment]
Thanks for the reminder on Top Priorities review @aahlenst, added to the agenda (and will keep as recurring).

**Comment by adamfarley** [comment]
**Additional Agenda Items**

**Actions from previous retros.**

Basically we need to know if these items are already Done, can be Ignored, or need to be Carried Over. This so we can close those antiquated issues.

George:
1) aarch git mirror jobs still fail due to shenandoah tags coming in and need a manual tidy up each time (Raised by: Martijn Verberg) (July 2020 Retrospective)
2) Raise issue to develop documentation for this problem: apt installers for 8u272 suffer a gap in update time which affects end users. (Volunteers: George & Stewart) (October 2020 Retrospective)
3) Host a call to discuss having a better visible release status like https://gist.github.com/aahlenst/bbb8ca9c87353e0c8928633961047340 (Volunteer: George Adams) (October 2020 Retrospective)
 (With all the different branches/release dates (think ARM on 8), it's super hard to track.)

Shelley:
1) Ensure that there is an overarching workflow/pipeline for each of the items in a release definition. (Raised by: Shelley Lambert) (April 2020 Retrospective) - Done (See epic in openjdk-build repo)
2) Verify each step in the flow. Currently we have this in place for the 'build component'. We build, then we run testing, but need it for every other component (docker, installers, documentation, website, etc). (Raised by: Shelley Lambert) (April 2020 Retrospective) - Done (See aforementioned epic)

**Unaddressed topics from January retro**
(Grouped by person most likely to own the next action.)

Andreas:
1) Would be great if people could help collect topics for the release announcement. Example AdoptOpenJDK/blog#561 (Raised by: Andreas) (Retrospective suggested raising an issue to contain these topics. The only suggested way of motivating folks to put an entry here every time was to chase them.) - Done. Zurich students are making this easier, and Andreas is handling the list creation.
2) Apart from that, we should think about how we can introduce proper change logs in each project. E.g. a file like https://github.com/square/okhttp/blob/master/CHANGELOG.md and not a commit history.
For example, we lost the statement about the GCC 7.5 update in the release announcement because I was apparently the only person that could remember the change. (Raised by: Andreas) (Ditto as above.)

Martijn:
1) IBM RHEL 6 machine missing some pre-reqs for language tests. (Raised by: Martijn) (Retrospective recommended you raise issue to address this.)

**Comment by adamfarley** [comment]
Release checklists: [automated](https://github.com/AdoptOpenJDK/TSC/issues/178) and [manual](https://github.com/AdoptOpenJDK/TSC/issues/215).
- What do people think about these?
- Does the latter have value while the former is in development?
- If yes, any objection to the restructuring proposed by the former? Is there a better way?
- What work is needed to make either/both happen?

**Comment by M-Davies** [comment]
> Apart from that, we should think about how we can introduce proper change logs in each project. E.g. a file like https://github.com/square/okhttp/blob/master/CHANGELOG.md and not a commit history.
For example, we lost the statement about the GCC 7.5 update in the release announcement because I was apparently the only person that could remember the change. (Raised by: Andreas) (Ditto as above.)

Maybe with [GitHub releases](https://github.com/AdoptOpenJDK/openjdk-build/releases)? I'll defer judgement until the meeting however

**Comment by smlambert** [comment]
March 22nd recording [link](https://bluejeans.com/s/GeIHK4Ih4EE) 

Link to next meeting's details and proposed agenda: https://github.com/AdoptOpenJDK/TSC/issues/217

**Comment by adamfarley** [comment]
Thanks Shelley 👍 

So we've learned that, even if someone else starts the meeting and starts the recording, Shelley still gets the link. FYI.
