### ISSUE TITLE
Proposal: Scale back Hotspot JDK8 zLinux Effort

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/TSC#218]
**Summary**
It is proposed that we scale back our efforts on zLinux for JDK8 on Hotspot, reducing or cancelling testing, and even halting all future builds.

**Reasoning**
Hotspot JDK8 on zLinux has no JIT, and thus it takes a lot of s390 machine time to run any tests. Time better spent elsewhere.

[For example](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1051#issuecomment-804359944), TestAESMain.java takes 2 mins (max) on other platforms/VMs, and takes 6 hours on Hotspot JDK8.

Also, given that it's so slow without the JIT, do we have evidence that anyone wants this build, given that it's not listed as a supported build platform [upstream](https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms)?

**Comment by smlambert** [comment]
jdk8/hotspot on zLinux was certainly one of the reasons why I opened this issue https://github.com/AdoptOpenJDK/TSC/issues/186 to establish criteria by which we choose to build/test/distribute a platform.

I am in favour of no longer building / testing / distributing the jdk8/hotspot/zlinux build.  

Short of that, I am in favour of disabling testing on this platform, continuing to build and not publish/distribute it (as we would not test it). 
 
Since this product under test has no JIT enabled, it is a resource hog, I can only imagine how long it would take to run JCK suite on it.  By choosing to no longer build and test it, we would free up machine resources for the other versions/impls.

@AdoptOpenJDK/tsc - please provide feedback here, 3 options for jdk8/hotspot/zlinux:

1. stop build/test/distribute
2. build it, but stop testing/distributing it
3. continue build/test/distribute it (death by a thousand timeouts)

I vote for 1) to stop building/testing/distributing jdk8 hotspot on zLinux

**Comment by tellison** [comment]
Agreed.  I doubt that binary is used broadly given its limitations, and we have a newer binary to bootstrap further work.  So I also suggest following option (1).

**Comment by sxa** [comment]
I'd almost keep it purely so we can do any comparisons with OpenJ9 if required. JCK would probably take a while though.

My honest gut feel: I'd generally consider myself in favour of retaining it but only running `sanity.openjdk` on the release. I like the fact we have a wide platform coverage and having Linux/s390x missing from Temurin in the list would be a shame. Perhaps I shouldn't be nostalgic, and I would understand if we decided not to (or built it and made it available as a nightly only)

**Comment by adamfarley** [comment]
Based on [today's ACC](https://github.com/AdoptOpenJDK/TSC/issues/217), we'll continue to build these, but will reduce the regular testing to sanity.openjdk only.

Todo: Will raise a pipelines repo issue to cover this work in a few minutes, once the ACC finishes.

Edit: [Issue raised.](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/issues/116)

**Comment by karianna** [comment]
Closing as the decision was made.
