### ISSUE TITLE
Reason for lack of Windows 32-bit builds?

### ISSUE THREAD

**Issue by sihaisz** [AdoptOpenJDK/TSC#30]
Apart from Open9 JDK8 builds there are no Windows 32-bit builds. From what I can gather the capability is there for both later JDKs and Hotspot VM but it is not being done.

We have some users still on 32-bit Windows and apparently "it's 2018" is not a strong enough reason for them to upgrade and we need to continue supporting them. So I'm wondering what the reason is for the lack of 32-bit.

Some possible reason's I can think of:

- There are current issues with 32-bit OpenJDK9+/Hotspot

- Do not want to take on the cost of supporting it for the future

- Do not want to spend resources building and testing on this architecture

- Nobody asked before and well, "it's 2018"

**Comment by karianna** [comment]
Hi @sihaisz 

Unfortunately in 2018 Win32 is not a platform that any OpenJDK vendor is willing to support professionally as there's not enough of a commercial market for it anymore.

Support is therefore on a best effort basis by community volunteers who are interested in supporting things like the Lego Mindstorm platform. This is true for both OpenJ9 and Hotspot.

Adopt is focussed on providing a build and test farm so that Win32 binaries can be built and tested, but we do not directly provide source code patches to ensure that it can be maintained going forwards (that's up to various volunteers at OpenJDK and/or OpenJ9).

If some sponsorship came through to materially support Win32 builds we can ensure that it goes to the volunteers working directly on Win32 at OpenJDK / OpenJ9 to allow them to spend more time and effort on it.

Happy to discuss on a call if that suits!

**Comment by sihaisz** [comment]
Thanks for the quick and detailed reply!

I'll reach out to the people in my org that make these types of decisions and get back to you.

**Comment by julian-alarcon** [comment]
Amazon Corretto is providing 32 bits releases: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by karianna** [comment]
> Amazon Corretto is providing 32 bits releases: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

As are we at AdoptOpenJDK now :-)
