### ISSUE TITLE
Create a mailing list for announcements

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#32]

**Comment by gdams** [comment]
TSC voted for setting up GSuite to host this

**Comment by fredrikjonson** [comment]
Over a year since the TCS seemingly agreed on a solution for this and still no sign of a announcement mailing list. Is there anything a bystander like me can do to help making this happen?

A small tip to others who wish to keep track of releases in the mean time: You can subscribe to release notifications on the binary repositories. For example to check for new openjdk-8 releases, watch: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases

**Comment by karianna** [comment]
I propose creating a Google group backed mailing list called `adoptopenjdk-announce`

**Comment by karianna** [comment]
We've created a list - for discussion at TSC

**Comment by smlambert** [comment]
Did we actually discuss this and this issue be closed, or its been forgotten?  I can not recall.  

@karianna - do you know what is the status on this one?

**Comment by aahlenst** [comment]
I'm not Martijn, but I remember: We decided not to create one before moving to the EF (because that's always about to happen), also because the EF has a nice mailing list infra and we do not.

**Comment by smlambert** [comment]
Yes, given mailing lists are a 'thing' at EF, closing this one.

**Comment by timkofu** [comment]
I was just at EF and this is all their mailing lists https://accounts.eclipse.org/mailing-list

Which one do I subscribe to for Temurin LTS main+patch releases?

**Comment by karianna** [comment]
REcommend https://accounts.eclipse.org/mailing-list/temurin-dev for now
