### ISSUE TITLE
Request for 64 bit intel server to be purchased and hosted a inspira

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#72]
Now that the delphix sponsorship money has come through we need to look at building solaris on intel. The easiest way to do this would be to buy a 64 bit intel server and run ESXi on it. This would also allow us to host other OS's such as windows or 32 bit linux.

My initial request is for £2000 to purchase a server and then £200 p/m to host it.

**Comment by cmdc0de** [comment]
Could look at something like: https://www.connectria.com/technology/solaris-hosting/ rather than hosting your own.  Leave the space/power issues to someone else?
Just just a dedicated server platform like server4u or OVH, we 'rent' the server from them we can then run virtualization tech under it.  Maybe useful for the future to run different tests until different virtualization especially when/if we get into smaller platforms (embedded arm devices etc). 

Is there a specific reasons for ESXi?
Some other thoughts: KVM direct or QEMU directly simple scripts rather than an orchestration engine like Openstack.

**Comment by gdams** [comment]
@cmdc0de I've tried contacting connectria before but they no longer provide solaris hosting. To clarify the server we purchased would be collocated at inspira in one of their racks so we wouldn't need to worry about power/space. It's where we currently host my solaris sparc server too.

**Comment by gdams** [comment]
closing for now
